name: build-and-test
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      ubuntu:
        image: ubuntu:16.04
    steps:
      - name: Check Ubuntu version
        run: lsb_release -a
    
