name: build-and-test
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    services:
     ubuntu:
        image: ubuntu:16.04
    steps:
      - name: Check ubuntu version
        run: lsb_release -a
    
