name: build-and-test
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
        image: ubuntu:16.04
    steps:
      - name: Check Ubuntu version
        run: cat /etc/*-release
    
