name: build-and-test
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        
      - name: Check ubuntu version
        run: lsb_release -a
    
